export const AFFILIATE_ROUTES: Record<string, string> = {
  trip:             "https://trip.tpk.mx/kNeRf3uG",
  viator:           "https://klook.tpk.mx/VRVE9lmH",
  agoda:            "https://hotels.tpk.mx/hR2UXCvP",
  "agoda-search":   "https://agoda.tpk.mx/FsXPsYpR",
  expedia:          "https://expedia.tpk.mx/FKbT2SL1",
  tripadvisor:      "https://tripadvisor.tpk.mx/kwPMJXls",
  omio:             "https://omio.tpk.mx/m2Vuvu9x",
  visitorscoverage: "https://visitorscoverage.tpk.mx/7SUkOHQg",
  "12go":           "https://12go.tpk.mx/9YrONWy1",
  kiwi:             "https://kiwi.tpk.mx/SOmJIBgC",
  cheapoair:        "https://cheapoair.tpk.mx/kyNjZQV5",
  hostelworld:      "https://hostelworld.tpk.mx/YzAvr3Xd",
  hotels:           "https://hotels.tpk.mx/hR2UXCvP",
  wegotrip:         "https://wegotrip.tpk.mx/892NRzxM",
  searadar:         "https://searadar.tpk.mx/mLgcGNF8",
  klook:            "https://klook.tpk.mx/inrJ4UBZ",
  localrent:        "https://localrent.tpk.mx/OOoXLJrc",
  tiqets:           "https://tiqets.tpk.mx/xoSnrtV2",
  ekta:             "https://ektatraveling.tpk.mx/CAjk83IF",
  airalo:           "https://www.airalo.com/?partner=himaltohorizon",
  aviasales:        "https://aviasales.tpk.mx/fcCA3RSZ",
};

export const PARTNER_LABELS: Record<string, string> = {
  trip:             "Trip.com",
  viator:           "Klook",
  agoda:            "Hotels.com",
  "agoda-search":   "Agoda",
  expedia:          "Expedia",
  tripadvisor:      "TripAdvisor",
  omio:             "Omio",
  visitorscoverage: "Visitors Coverage",
  "12go":           "12Go Asia",
  kiwi:             "Kiwi.com",
  cheapoair:        "CheapOair",
  hostelworld:      "Hostelworld",
  hotels:           "Hotels.com",
  wegotrip:         "WeGoTrip",
  searadar:         "SeaRadar",
  klook:            "Klook",
  localrent:        "Localrent",
  tiqets:           "Tiqets",
  ekta:             "EKTA",
  airalo:           "Airalo",
  aviasales:        "Aviasales",
};
