import type { PostSeed } from "./blog-seeds";

export const NEW_POSTS_2: PostSeed[] = [

  // ═══════════════════════════════════════════════════════════
  // ASIA — additional
  // ═══════════════════════════════════════════════════════════

  {
    slug: "kerala-travel-guide",
    title: "Kerala Travel Guide: God's Own Country Done Right",
    excerpt: "Kerala is the antidote to northern India's chaos — backwaters, spice plantations, Ayurvedic resorts, and a cuisine that makes everywhere else look lazy.",
    seo_title: "Kerala Travel Guide 2025 | Backwaters, Munnar, Beaches & When to Go",
    seo_description: "Complete Kerala travel guide: houseboats on the backwaters, Munnar tea estates, Varkala beach, Fort Kochi, best season, Ayurveda resorts, and travel tips.",
    category: "destination-guide",
    destination_name: "Kerala",
    destination_iata: "COK",
    country: "India",
    region: "South Asia",
    continent: "Asia",
    hero_emoji: "🌴",
    best_time_to_visit: "November–February (dry, cool, ideal)",
    tags: ["india", "kerala", "backwaters", "ayurveda", "south-india", "kochi"],
    reading_time_mins: 9,
    featured: false,
    published: true,
    content_json: [
      { t: "p", v: "Kerala stretches down India's southwestern tip between the Western Ghats and the Arabian Sea. It's India's most literate state, its most visited state for domestic tourism, and by common international consensus, its most relaxed. The backwaters — a 900 km network of lakes, lagoons, and canals — are genuinely unlike anything else on earth. The food is coconut-rich and extraordinary. The people are hospitable in a way that doesn't feel transactional." },
      { t: "facts", v: [
        { k: "Best time", val: "Nov–Feb (dry season, 22–30°C)" },
        { k: "Avoid", val: "Jun–Aug (heavy monsoon — beautiful but many boats stop running)" },
        { k: "Airports", val: "Kochi (COK) — main gateway; Trivandrum (TRV) for south Kerala" },
        { k: "Key regions", val: "Kochi (city + history), Alleppey/Backwaters, Munnar (hills/tea), Varkala (beach/cliffs), Wayanad (wildlife)" },
        { k: "Budget", val: "$35–$70/day (mid-range); houseboat stays $80–$200/night" },
        { k: "Distance from Goa", val: "Train 14 hrs south along the Konkan coast — one of India's most scenic rail journeys" },
      ]},
      { t: "h2", v: "When to Go — and the Monsoon Calculation" },
      { t: "p", v: "November through February is universally considered ideal — temperatures moderate, humidity low, and the backwaters calm and navigable. October is excellent and less crowded. March and April heat up gradually. The southwest monsoon arrives in June and lasts through September — this is the season Ayurvedic retreats actually prefer (the humidity enhances treatment efficacy), but regular tourism is disrupted. The northeast monsoon hits October–November and is lighter." },
      { t: "h2", v: "The Must-Do Experiences" },
      { t: "ol", v: [
        "Houseboat overnight on the backwaters (Alleppey/Alappuzha) — the traditional rice barge (kettuvallam) converted into a floating hotel. Book through an established operator; avoid the cheapest options (which are poorly maintained). Sunrise on the backwaters is extraordinary.",
        "Fort Kochi — the old colonial quarter of Kochi (Cochin). Portuguese, Dutch, and British architecture side by side. Chinese fishing nets on the waterfront (unique to Kerala). Kathakali dance performance in the evening.",
        "Munnar tea estates — a highland town at 1,600 m surrounded by rolling tea plantations. The drive up from Kochi through rubber and spice plantations is as good as the destination.",
        "Varkala beach — a cliff-top beach with restaurants and guesthouses overlooking the Arabian Sea. More relaxed than Goa. Good swimming September–April.",
        "Thekkady wildlife sanctuary — the Periyar Tiger Reserve. Boat trips on the lake for elephant and deer sightings. Kerala's best wildlife-watching option.",
        "Ayurvedic treatment — Kerala is the home of Ayurveda. A 60–90 minute massage at a quality retreat costs $30–$50. A week-long Panchakarma detox retreat costs $500–$1,500.",
      ]},
      { t: "tip", v: "The train journey along Kerala's coast — between Kochi and Trivandrum, or the spectacular Konkan Railway north to Goa — runs alongside the sea for long sections. Book a window seat on the sea side and travel in daylight. One of India's genuinely great rail experiences." },
    ],
  },

  {
    slug: "china-travel-guide",
    title: "China Travel Guide: Where to Start, How to Plan, What to Expect",
    excerpt: "China is simultaneously the easiest and hardest travel destination on earth. Here's how to navigate it — visas, apps, the Great Wall, and beyond.",
    seo_title: "China Travel Guide 2025 | Visa, Best Cities, When to Go & Practical Tips",
    seo_description: "Complete China travel guide for 2025: visa-free updates, Beijing, Shanghai, Xi'an, the Great Wall, bullet trains, VPN requirements, and the best time to visit.",
    category: "destination-guide",
    destination_name: "China",
    destination_iata: "PEK",
    country: "China",
    region: "East Asia",
    continent: "Asia",
    hero_emoji: "🐉",
    best_time_to_visit: "April–June and September–October",
    tags: ["china", "beijing", "shanghai", "asia", "great-wall", "travel-guide"],
    reading_time_mins: 11,
    featured: false,
    published: true,
    content_json: [
      { t: "p", v: "China is a country of superlatives: the world's longest history of continuous civilization, the longest human-built structure, the world's largest high-speed rail network, the most active construction programme on earth. It is also a country of genuine digital isolation — Google, WhatsApp, Instagram, and most Western apps don't work without a VPN. With preparation, it's extraordinarily rewarding. Without it, it can be deeply frustrating." },
      { t: "facts", v: [
        { k: "Visa (2025 update)", val: "Many nationalities now have visa-free access for 15–30 days — check MOFCOM list before applying for a visa" },
        { k: "Best season", val: "Apr–Jun and Sep–Oct (comfortable, lower pollution)" },
        { k: "Avoid", val: "Chinese New Year (Jan/Feb) — massive domestic travel disruption; golden weeks (Oct 1–7, May 1–5)" },
        { k: "Currency", val: "Chinese Yuan/Renminbi (CNY) — payment by WeChat Pay and Alipay is near-universal; carry some cash for rural areas" },
        { k: "Internet", val: "Google, Facebook, Instagram, WhatsApp, and most Western apps blocked — get a VPN before entering China" },
        { k: "Rail", val: "China's HSR bullet trains are extraordinary — Beijing to Shanghai in 4.5 hrs, Shanghai to Xi'an in 6.5 hrs" },
        { k: "Best first cities", val: "Beijing + Shanghai + Xi'an as a 10–14 day first trip" },
      ]},
      { t: "warn", v: "Set up a VPN on your devices BEFORE you arrive in China — the app stores that VPNs are distributed through are themselves blocked inside China. ExpressVPN and Astrill are the most reliable options for China. Don't rely on free VPNs — they rarely work." },
      { t: "h2", v: "When to Go" },
      { t: "p", v: "April–June is the sweet spot: comfortable temperatures (18–25°C in Beijing), spring flowers, and manageable crowd levels. September and October are equally good — harvest colours in northern China, clearer air. July and August are hot and humid nationwide. The Golden Week holidays (October 1–7 and May 1–5) see 500 million domestic travellers moving around the country simultaneously — prices triple and everything is packed." },
      { t: "h2", v: "The Essential Itinerary: Beijing + Xi'an + Shanghai" },
      { t: "ol", v: [
        "Beijing (4 days): Forbidden City (book timed entry online), Tiananmen Square, Temple of Heaven, the best hutong (old alley) neighbourhoods (Nanluoguxiang, Wudaoying), and the Great Wall at Mutianyu (restored, less crowded than Badaling)",
        "The Great Wall: Mutianyu is the best section for most visitors — restored, scenic, accessible (1.5 hrs from Beijing). Jiankou is the unrestored, dramatic version for the fit and brave.",
        "Xi'an by bullet train (5 hrs from Beijing): The Terracotta Army is one of the genuine wonders of the ancient world — 8,000 individually crafted soldiers in battle formation. Go at opening. The Muslim Quarter food market for evening dinner.",
        "Shanghai by bullet train (6.5 hrs from Xi'an or 4.5 hrs from Beijing): The Bund waterfront at night, the French Concession neighbourhood, the Yu Garden bazaar. China's most cosmopolitan city — easier for Western visitors than Beijing.",
      ]},
      { t: "h2", v: "Payment and Practicalities" },
      { t: "ul", v: [
        "WeChat Pay and Alipay: China has become near-cashless. Many restaurants and shops don't accept foreign bank cards. Foreigners can now add international cards to WeChat Pay (since 2023 update) — set this up before you go.",
        "Cash backup: carry CNY 500–1,000 in cash for situations where mobile pay isn't accepted (rural areas, small vendors). Change currency at Bank of China at the airport.",
        "Translation: Download Google Translate offline language pack before you leave (since Google is blocked in China, it won't update). Baidu Translate works inside China.",
        "Taxis: Didi (China's Uber) works with international cards. The app interface can be challenging — have your hotel write your destination in Chinese characters.",
        "Mandarin: A handful of Mandarin phrases (ni hao, xie xie, duo shao qian?) open doors significantly. Written Chinese is universal across all dialects.",
      ]},
    ],
  },

  {
    slug: "beijing-travel-guide",
    title: "Beijing Travel Guide: Ancient Palaces, Street Food & the Great Wall",
    excerpt: "Beijing is 3,000 years of history stacked into one sprawling, relentless, extraordinary city. The Forbidden City alone is worth a day. The Great Wall is worth a lifetime.",
    seo_title: "Beijing Travel Guide 2025 | Forbidden City, Great Wall & Hutong Neighbourhoods",
    seo_description: "Complete Beijing travel guide: Forbidden City tickets, Great Wall sections (Mutianyu vs Badaling), best hutong neighbourhoods, Peking duck, and when to visit.",
    category: "destination-guide",
    destination_name: "Beijing",
    destination_iata: "PEK",
    country: "China",
    region: "East Asia",
    continent: "Asia",
    hero_emoji: "🏯",
    best_time_to_visit: "April–June and September–October (spring/autumn)",
    tags: ["china", "beijing", "great-wall", "forbidden-city", "asia", "hutong"],
    reading_time_mins: 10,
    featured: false,
    published: true,
    content_json: [
      { t: "p", v: "Beijing is China at its most imperial. The Forbidden City housed 24 emperors across five centuries. The Summer Palace was the empire's pleasure garden. The Great Wall — visible from the hilltops that ring the city — is 2,000 years old and still unambiguously one of the greatest things humans have ever built. The city of 21 million people that surrounds all of this is simultaneously ultramodern and, in its back alleys (hutong), unchanged since the Ming dynasty." },
      { t: "facts", v: [
        { k: "Best season", val: "Apr–May and Sep–Oct (18–26°C, lower pollution, comfortable)" },
        { k: "Avoid", val: "Jan–Feb (bitter cold, -10°C); Jul–Aug (35°C, humid, heavy rain); Oct 1 Golden Week" },
        { k: "Airport", val: "Beijing Capital (PEK) and Beijing Daxing (PKX) — check which your airline uses" },
        { k: "From airport", val: "Airport Express train from PEK to city centre: 30 min, ¥25" },
        { k: "Forbidden City tickets", val: "Must be booked online in advance at dpm.org.cn — daily visitor cap of 80,000" },
      ]},
      { t: "h2", v: "The Great Wall: Which Section?" },
      { t: "ul", v: [
        "Mutianyu (most recommended) — 70 km from Beijing, 2 hrs by car or organised tour. Well-restored, scenic, far fewer crowds than Badaling. Cable car up, toboggan down (optional). At least 4–5 hrs on the wall.",
        "Badaling — the most visited section in the world. Heavily restored, enormous crowds, tourist infrastructure. Easy access by bullet train from Beijing North (1 hr). Fine but not the best experience.",
        "Jiankou (wild/unrestored) — spectacular, challenging, requires hiking experience and a guide. The section where the wall crumbles dramatically down a steep ridge. Jaw-dropping photography.",
        "Simatai (evening option) — partially restored section with the only evening opening. The illuminated wall after dark is extraordinary. Book weeks ahead.",
      ]},
      { t: "h2", v: "The Best of Beijing" },
      { t: "ol", v: [
        "Forbidden City — 980 buildings, 8,730 rooms, the largest palace complex on earth. Budget 4–5 hours. The inner courts (Empress's quarters) are less crowded than the main axis.",
        "Temple of Heaven (Tiantan Park) — where emperors prayed to heaven for good harvests. The Hall of Prayer for Good Harvests is architecturally flawless. Come early morning to watch Beijingers doing tai chi, flying kites, and singing opera in the park.",
        "Nanluoguxiang hutong — the most accessible old alley neighbourhood. Craft shops, street food, coffee bars in old courtyard houses. Busy but genuine.",
        "798 Art District — a decommissioned weapons factory turned into China's most important contemporary art hub. Compelling juxtaposition of Bauhaus industrial architecture and modern Chinese art.",
        "Peking Duck dinner — Da Dong or Quanjude are the institutions. Order the full ritual: duck carved tableside, served with spring pancakes, hoisin sauce, cucumber, and scallions.",
        "Wangfujing night market — street food including the famous scorpions-on-a-stick (more tourist theatre than local food, but worth seeing).",
      ]},
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // SOUTH AMERICA — additional
  // ═══════════════════════════════════════════════════════════

  {
    slug: "sao-paulo-travel-guide",
    title: "São Paulo Travel Guide: Concrete Jungle, World-Class Food, and Hidden Art",
    excerpt: "São Paulo is not pretty in the conventional sense — 23 million people, a sea of skyscrapers, perpetual traffic. But it's South America's cultural and culinary capital. Here's how to see the best of it.",
    seo_title: "São Paulo Travel Guide 2025 | Best Neighbourhoods, Restaurants & Things to Do",
    seo_description: "Complete São Paulo travel guide: Paulista Ave, Vila Madalena, Liberdade, MASP, best restaurants, nightlife, safety tips, and when to visit.",
    category: "destination-guide",
    destination_name: "São Paulo",
    destination_iata: "GRU",
    country: "Brazil",
    region: "South America",
    continent: "South America",
    hero_emoji: "🌆",
    best_time_to_visit: "April–October (drier, cooler, more comfortable)",
    tags: ["brazil", "sao-paulo", "south-america", "food", "city-guide", "art"],
    reading_time_mins: 9,
    featured: false,
    published: true,
    content_json: [
      { t: "p", v: "São Paulo is the city that earns you. It's not immediately beautiful, it doesn't have a beach, and its traffic can be genuinely paralysing. But it has the best restaurant scene in South America — arguably in the Western Hemisphere — a cultural programme that rivals London, and neighbourhoods with genuine character that most tourists never find. Give it three days and it will grab you." },
      { t: "facts", v: [
        { k: "Population", val: "23 million (greater metro area) — largest city in the Southern Hemisphere" },
        { k: "Airports", val: "Guarulhos (GRU) — international, 35 km from city; Congonhas (CGH) — domestic, within city" },
        { k: "Best season", val: "Apr–Oct (drier, 15–22°C) — summer (Dec–Mar) is hot, humid, and rainy" },
        { k: "Currency", val: "Brazilian Real (BRL)" },
        { k: "Daily budget", val: "USD $50–$90 (mid-range)" },
        { k: "Safety", val: "Like all Brazilian cities, requires awareness. Stick to known neighbourhoods at night. Use Uber." },
      ]},
      { t: "h2", v: "The Neighbourhoods Worth Knowing" },
      { t: "ul", v: [
        "Vila Madalena — the arts and bohemian quarter. Street murals (the Beco do Batman alley has the best concentration in the city), galleries, craft beer bars, and Saturday antiques market.",
        "Pinheiros and Jardins — upscale, leafy, restaurant-dense. Rua Oscar Freire is São Paulo's luxury shopping street. The Museu de Arte de São Paulo (MASP) is on nearby Avenida Paulista.",
        "Liberdade — São Paulo's Japanese-Brazilian neighbourhood (the largest Japanese diaspora community outside Japan). The Sunday street market is extraordinary.",
        "Centro Histórico — the old city centre. More gritty but with genuine historic buildings: the Pátio do Colégio (where São Paulo was founded in 1554), Mercado Municipal (the market hall with the best mortadella sandwich in the world).",
        "Itaim Bibi — the finance and upscale restaurant district. Many of the best Japanese and contemporary restaurants are here.",
      ]},
      { t: "h2", v: "Top Things to Do" },
      { t: "ol", v: [
        "MASP (Museu de Arte de São Paulo) — the suspended glass box above Paulista Ave is iconic. Inside: Raphael, Rembrandt, Monet, Picasso, and the best Latin American art collection in the country.",
        "Ibirapuera Park — São Paulo's Central Park, 158 hectares of gardens, museums, and Sunday picnics. The Museu de Arte Moderna and Museu Afro Brasil are both inside.",
        "Mercado Municipal (Mercadão) — the 1933 covered market hall with stained glass windows. The mortadella sandwich at Bar do Mané inside is a city institution.",
        "Beco do Batman — Vila Madalena's alley entirely covered in constantly evolving street murals. Free, open 24 hrs.",
        "São Paulo restaurant scene — the city has 15,000+ restaurants. Dom (Alex Atala) and Mocotó are the headline names; the Japanese restaurants in Liberdade and Itaim are unmatched outside Japan.",
      ]},
      { t: "tip", v: "São Paulo is a city of Ubers and Ubers only. The traffic is legendary but unavoidable. Book your accommodation in Pinheiros, Jardins, or Vila Madalena — these three neighbourhoods are walkable to each other and contain 80% of what's worth visiting." },
    ],
  },

  {
    slug: "salvador-bahia-guide",
    title: "Salvador, Bahia: The Heart of Afro-Brazilian Culture",
    excerpt: "Salvador is Brazil's first colonial capital and its most African city — 80% of the population is of African descent. The music, the food, the Candomblé ceremonies, and the Pelourinho streets are extraordinary.",
    seo_title: "Salvador Bahia Travel Guide 2025 | Pelourinho, Carnival & Afro-Brazilian Culture",
    seo_description: "Complete Salvador Bahia guide: Pelourinho UNESCO historic centre, Carnival dates, best beaches, Afro-Brazilian cuisine, safety tips, and when to visit.",
    category: "destination-guide",
    destination_name: "Salvador",
    destination_iata: "SSA",
    country: "Brazil",
    region: "South America",
    continent: "South America",
    hero_emoji: "🥁",
    best_time_to_visit: "September–March (warmer, Carnival Feb/Mar); avoid Apr–Jul (rain)",
    tags: ["brazil", "salvador", "bahia", "carnival", "afro-brazilian", "south-america"],
    reading_time_mins: 8,
    featured: false,
    published: true,
    content_json: [
      { t: "p", v: "Salvador de Bahia was Brazil's first capital and the largest slave port in the Americas — a fact that defines everything about the city. Eighty percent of Salvador's population is of African descent, and the Yoruba, Fon, and Bantu cultural traditions brought across the Atlantic during 300 years of the slave trade survived here in forms found nowhere else in the world: the Candomblé religion, the capoeira martial art, the acarajé street food, the axé and samba-reggae music." },
      { t: "facts", v: [
        { k: "Best time", val: "Sep–Jan (warm, drier, 26–30°C)" },
        { k: "Carnival", val: "February or March — Salvador's Carnival is the largest street party in the world (2 million people/day, 6 days)" },
        { k: "Avoid", val: "Apr–Jun (heaviest rain season)" },
        { k: "Airport", val: "Deputado Luís Eduardo Magalhães (SSA)" },
        { k: "Neighbourhoods", val: "Pelourinho (historic, tourist), Barra (beaches, bars), Rio Vermelho (local, restaurants)" },
        { k: "Budget", val: "$40–$70/day (mid-range)" },
      ]},
      { t: "h2", v: "What to See and Do" },
      { t: "ol", v: [
        "Pelourinho (UNESCO World Heritage) — the restored colonial centre on a hilltop above the bay. Colourful Baroque churches, cobblestone streets, live music spilling from bars. Visit the Largo do Pelourinho square on Tuesday evenings when Olodum (the famous drumming group) performs.",
        "Elevador Lacerda — the 1873 Art Deco elevator connecting the upper and lower city. Panoramic bay views from the top.",
        "Igrejas (Churches) — the Igreja Nosso Senhor do Bonfim (the most important church in Bahia) and the Catedral Basílica are both extraordinary.",
        "Capoeira — street performances and formal academies throughout Pelourinho. The martial art-dance-music form developed by enslaved Africans is mesmerizing to watch.",
        "Mercado Modelo — the old customs house converted into a craft market at the base of the Lacerda elevator. Acarajé (fried bean fritters with shrimp) from vendors outside.",
        "Beaches — Barra (surf, sunset at the lighthouse) and the further northern beaches (Stella Maris, Flamengo) are the best. Avoid the beaches close to Pelourinho.",
      ]},
      { t: "h2", v: "Bahian Food: The Best Cuisine in Brazil" },
      { t: "p", v: "Most food critics consider Bahian cuisine to be Brazil's finest — a fusion of West African cooking techniques (dendê palm oil, okra, coconut milk) with Portuguese and indigenous ingredients. Essential dishes: moqueca (fish/seafood stew in coconut milk and dendê), acarajé (fried black-eyed pea fritters with vatapá shrimp paste), bobó de camarão (shrimp in cassava cream). Eat all three at least once." },
    ],
  },

  {
    slug: "lima-cusco-peru-guide",
    title: "Lima & Cusco: Peru's Two Essential Cities",
    excerpt: "Lima is South America's most underrated food city. Cusco is the gateway to the Inca heartland and the starting point for Machu Picchu. Together they make Peru's essential two-city circuit.",
    seo_title: "Lima & Cusco Travel Guide 2025 | Food, Inca History & Altitude Tips",
    seo_description: "Complete guide to Lima and Cusco: Miraflores, Barranco, altitude sickness prevention, Sacred Valley, Pisac market, how to get to Machu Picchu, and best restaurants.",
    category: "destination-guide",
    destination_name: "Lima & Cusco",
    destination_iata: "LIM",
    country: "Peru",
    region: "South America",
    continent: "South America",
    hero_emoji: "🦙",
    best_time_to_visit: "April–October (dry season; June–August ideal)",
    tags: ["peru", "lima", "cusco", "south-america", "inca", "altitude", "food"],
    reading_time_mins: 10,
    featured: false,
    published: true,
    content_json: [
      { t: "p", v: "Peru is a country that earns superlatives from every direction. Lima has emerged as South America's premier food destination — with more restaurants on the Latin America's 50 Best list than any other city. Cusco is the former capital of the Inca Empire, a city of 3,400 m sitting in an Andean valley where Inca stonework is embedded into every colonial building. Between them lies the Sacred Valley and the trail to Machu Picchu." },
      { t: "facts", v: [
        { k: "Lima altitude", val: "154 m — no altitude issues; arrive here first" },
        { k: "Cusco altitude", val: "3,400 m — acclimatise 2–3 days before heading higher" },
        { k: "Best season", val: "Apr–Oct (dry season); Jun–Aug clearest skies but coldest nights at altitude" },
        { k: "Rainy season", val: "Nov–Mar (Inca Trail closes in February for maintenance)" },
        { k: "Lima airport", val: "Jorge Chávez (LIM) — direct flights from most major hubs" },
        { k: "Lima → Cusco", val: "90-min flight (~$60–$120 on LATAM or Sky Airline)" },
        { k: "Currency", val: "Peruvian Sol (PEN) — ~3.75 PEN to 1 USD" },
      ]},
      { t: "h2", v: "Lima: Food Capital of South America" },
      { t: "p", v: "Lima's food scene is the legitimate reason to extend your stay here beyond the transit day most itineraries allow. The combination of Andean ingredients (40+ varieties of potato, quinoa, amaranth), Pacific seafood, and Nikkei/Chifa (Japanese-Peruvian and Chinese-Peruvian fusion) has produced a cuisine unlike any other. The best neighbourhoods — Miraflores and Barranco — are safe, walkable, and beautiful on the Pacific clifftop." },
      { t: "ul", v: [
        "Stay in Miraflores (safe, cliff-top park, Larcomar mall on the ocean) or Barranco (bohemian, arts scene, best nightlife)",
        "Central (Virgilio Martínez) — consistently rated Latin America's best restaurant. Book 2–3 months ahead.",
        "Maido (Mitsuharu Tsumura) — the world's best Nikkei (Japanese-Peruvian) restaurant. Book similarly far ahead.",
        "La Mar Cebichería — excellent, more accessible ceviche and tiradito. Go for lunch (cevicherías traditionally close by mid-afternoon).",
        "Huaca Pucllana — an ancient adobe pyramid in the middle of Miraflores, lit at night. Free to walk around the perimeter.",
        "Larco Museum — outstanding pre-Columbian gold and ceramics collection in a beautiful colonial mansion in Pueblo Libre.",
      ]},
      { t: "h2", v: "Cusco and the Altitude Reality" },
      { t: "p", v: "Cusco sits at 3,400 m. Altitude sickness (soroche) affects 30–40% of visitors on the first day — headache, nausea, fatigue. The standard advice: arrive slowly (fly Lima → Cusco, don't rush higher), drink coca tea (freely available and genuinely helpful), avoid alcohol for the first 48 hours, and take Diamox if recommended by your doctor. Most people feel fine by day 3." },
      { t: "ol", v: [
        "Qorikancha — the Inca Temple of the Sun. The Spanish built the Convent of Santo Domingo directly on top; the Inca stonework is still visible at the base. The contrast is the entire history of the Spanish conquest in one building.",
        "Plaza de Armas (Cusco) — the main square with the Cathedral and Iglesia de La Compañía. Surrounded by Inca foundations.",
        "San Pedro Market — the working local market, not for tourists. Quinoa, purple corn, chicha (fermented maize drink), and 40 varieties of potato.",
        "Sacred Valley day trip (Pisac, Ollantaytambo) — the Inca ruins at Pisac above the Sunday market, and the fortress-temple at Ollantaytambo, are both essential before Machu Picchu.",
      ]},
    ],
  },

  {
    slug: "colonia-del-sacramento-guide",
    title: "Colonia del Sacramento: Uruguay's Perfect Day Trip",
    excerpt: "Colonia del Sacramento is a Portuguese colonial gem on the Río de la Plata — just one hour by ferry from Buenos Aires. It's one of the easiest and most rewarding day trips in South America.",
    seo_title: "Colonia del Sacramento Travel Guide 2025 | Day Trip from Buenos Aires by Ferry",
    seo_description: "Complete guide to Colonia del Sacramento, Uruguay: the UNESCO colonial quarter, Buquebus ferry from Buenos Aires, what to do, where to eat, and staying overnight.",
    category: "destination-guide",
    destination_name: "Colonia del Sacramento",
    destination_iata: "MVD",
    country: "Uruguay",
    region: "South America",
    continent: "South America",
    hero_emoji: "⚓",
    best_time_to_visit: "Year-round (best: October–April)",
    tags: ["uruguay", "colonia", "ferry", "buenos-aires", "south-america", "unesco", "day-trip"],
    reading_time_mins: 6,
    featured: false,
    published: true,
    content_json: [
      { t: "p", v: "Colonia del Sacramento is 50 km across the Río de la Plata from Buenos Aires — and about 400 years removed in atmosphere. The Barrio Histórico (Historic Quarter) is Uruguay's only UNESCO World Heritage Site: a small Portuguese colonial town of cobblestone streets, 18th-century ruins, and Río de la Plata views that make Buenos Aires, visible on clear days, look impossibly far away. It's the perfect half-day or overnight escape from the Argentine capital." },
      { t: "facts", v: [
        { k: "From Buenos Aires", val: "Buquebus ferry from Dársena Norte, Puerto Madero: 1 hr (fast cat) or 3 hrs (slower)" },
        { k: "Ferry cost", val: "USD $40–$70 return (varies by season and speed)" },
        { k: "Best time", val: "Oct–Apr (warm, sunny — winters are cold and grey)" },
        { k: "Walking time", val: "The entire Historic Quarter can be walked in 2–3 hours" },
        { k: "Day trip viability", val: "Perfectly viable as a day trip from Buenos Aires" },
        { k: "Overnight", val: "Worth staying for a quieter, more atmospheric experience" },
      ]},
      { t: "h2", v: "What to Do in Colonia" },
      { t: "ol", v: [
        "Walk the Barrio Histórico — the entire colonial quarter takes about 2 hours. The Calle de los Suspiros (Street of Sighs) is the most photogenic street in Uruguay.",
        "Lighthouse climb (Faro Colonia) — 19th-century lighthouse with views over the Río de la Plata to Argentina on a clear day. Tiny admission fee.",
        "Plaza Mayor — the main square with the Portuguese Museum, the Ruins of the Convent of San Francisco, and the characteristic low colonial buildings around it.",
        "Waterfront walk — the river boulevard at sunset, watching the lights of Buenos Aires come on across the water, is one of the most quietly romantic things in South America.",
        "Rent a golf cart — the local tradition. A golf cart rental for 2 hrs ($15–$20) lets you putter around the historic quarter and waterfront. Slower than walking; completely charming.",
      ]},
      { t: "tip", v: "Book the Buquebus online at buquebus.com at least a few days ahead in peak season (December–January). The 1-hour fast catamaran is worth the extra cost over the 3-hour crossing. Arrive at the terminal 45 minutes before departure — passport control is required for the Uruguay border crossing even for this short crossing." },
    ],
  },

  {
    slug: "punta-del-este-guide",
    title: "Punta del Este: South America's St. Tropez",
    excerpt: "Punta del Este is where South Americans who can afford it go for summer. Beautiful beaches, yacht harbours, world-class restaurants, and the Casapueblo — here's what to know before you go.",
    seo_title: "Punta del Este Travel Guide 2025 | Beaches, When to Go & What to Expect",
    seo_description: "Complete Punta del Este guide: Playa Mansa vs Brava, La Barra, José Ignacio, best season, Casapueblo, and how to get there from Montevideo and Buenos Aires.",
    category: "destination-guide",
    destination_name: "Punta del Este",
    destination_iata: "PDP",
    country: "Uruguay",
    region: "South America",
    continent: "South America",
    hero_emoji: "⛵",
    best_time_to_visit: "December–February (high summer season); shoulder: Nov and Mar",
    tags: ["uruguay", "punta-del-este", "beach", "south-america", "luxury"],
    reading_time_mins: 7,
    featured: false,
    published: true,
    content_json: [
      { t: "p", v: "Punta del Este sits at the point where the Río de la Plata meets the Atlantic Ocean, 140 km east of Montevideo. It's Uruguay's — and arguably South America's — most glamorous resort: a slim peninsula of beaches, marinas, and high-rises that transforms from ghost town in May to the tightest party in the Southern Hemisphere in January. The international crowd of Argentines, Brazilians, and Europeans who summer here sustains restaurants and clubs that would hold their own in Ibiza." },
      { t: "facts", v: [
        { k: "Distance from Montevideo", val: "140 km — 2 hrs by bus or 1.5 hrs by car" },
        { k: "From Buenos Aires", val: "Buquebus direct ferry to Punta del Este (3.5 hrs) operates in summer season (Dec–Mar)" },
        { k: "High season", val: "Dec 15 – Feb 28 — very expensive, very crowded, very alive" },
        { k: "Shoulder", val: "Nov and Mar — still warm, prices 40% lower, beaches less packed" },
        { k: "Off season", val: "Apr–Oct — deserted. Most restaurants close. Peaceful in its own way." },
        { k: "Airport", val: "Laguna del Sauce (PDP) — small regional airport, limited connections" },
      ]},
      { t: "h2", v: "The Beaches: Mansa vs Brava" },
      { t: "p", v: "Punta del Este's peninsula has two distinct sides. Playa Mansa (facing the Río de la Plata) is sheltered, calm, and warm — ideal for families, swimming, and stand-up paddleboarding. Playa Brava (facing the Atlantic) is exposed to Atlantic swells, cooler, and better for surfing. The famous La Mano sculpture — five giant fingers emerging from the sand — is on Playa Brava, almost at the tip of the peninsula." },
      { t: "h2", v: "Beyond the Peninsula" },
      { t: "ul", v: [
        "Casapueblo (20 min west) — the whitewashed Mediterranean fantasy building designed by artist Carlos Páez Vilaró. Now a hotel and museum. The sunset ceremony here is a Punta institution.",
        "La Barra (10 km east) — a hipper, more bohemian beach town across a drawbridge. Better restaurants and bars than central Punta, more Argentine crowd.",
        "José Ignacio (35 km east) — a tiny, exclusive fishing village that has become South America's most expensive address. Low-key luxury. La Huella restaurant is among the best in Uruguay.",
        "Montevideo day trip — easy 2-hr bus connection. Good for breaking up a Punta stay with culture.",
      ]},
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // EUROPE — additional
  // ═══════════════════════════════════════════════════════════

  {
    slug: "florence-tuscany-guide",
    title: "Florence & Tuscany: Renaissance Art, Chianti Wine & Hilltop Villages",
    excerpt: "Florence is the most art-dense city on earth — a Renaissance painting or sculpture around every corner. Beyond the city, Tuscany unfolds into vineyards, cypresses, and medieval hill towns.",
    seo_title: "Florence & Tuscany Travel Guide 2025 | Uffizi, Chianti & Best Hill Towns",
    seo_description: "Complete Florence and Tuscany travel guide: Uffizi Gallery, Michelangelo's David, Chianti wine country, Siena, San Gimignano, when to visit, and where to stay.",
    category: "destination-guide",
    destination_name: "Florence",
    destination_iata: "FLR",
    country: "Italy",
    region: "Southern Europe",
    continent: "Europe",
    hero_emoji: "🎨",
    best_time_to_visit: "April–June and September–October",
    tags: ["italy", "florence", "tuscany", "art", "wine", "renaissance", "europe"],
    reading_time_mins: 10,
    featured: false,
    published: true,
    content_json: [
      { t: "p", v: "Florence (Firenze) was the centre of the Italian Renaissance — the city where Botticelli, Michelangelo, Leonardo, and Raphael all worked under Medici patronage. The result is an impossible concentration of masterworks: the Uffizi Gallery, the Accademia (Michelangelo's David), the Duomo and Baptistery, the Bargello sculpture museum. Beyond the city, Tuscany is the landscape of Renaissance paintings come to life — rolling vineyards, cypress allées, and walled medieval hill towns." },
      { t: "facts", v: [
        { k: "Best time", val: "Apr–Jun and Sep–Oct (20–26°C, crowds manageable, countryside lush/golden)" },
        { k: "Avoid", val: "Jul–Aug (35°C+, most crowded period in a city built for crowds; Tuscany roads packed)" },
        { k: "Airport", val: "Florence (FLR, small) or Pisa (PSA, 80 min by train — budget airline hub)" },
        { k: "Train to Florence", val: "High-speed train from Rome: 1.5 hrs; from Venice: 2 hrs; from Milan: 1.75 hrs" },
        { k: "Day trip from Florence", val: "Siena (1.5 hrs by bus), San Gimignano (1.5 hrs), Cinque Terre (2 hrs by train)" },
      ]},
      { t: "h2", v: "The Florence Must-Sees (With Booking Strategy)" },
      { t: "ol", v: [
        "Uffizi Gallery — the greatest collection of Italian Renaissance painting: Botticelli's Birth of Venus, Caravaggio, Titian, Raphael. Book timed entry at uffizi.it weeks ahead in peak season. Allow 3–4 hours.",
        "Accademia Gallery — Michelangelo's David (the original, 5.17 m tall). Worth a short visit of 60–90 minutes. Book ahead.",
        "Duomo (Cathedral) — Brunelleschi's dome is the most important engineering achievement of the Renaissance. Climb it (pre-book) for the best view of Florence. The exterior and Baptistery are free.",
        "Oltrarno neighbourhood — the 'other side of the Arno'. More authentic, less touristed. Pitti Palace and Boboli Gardens, the Brancacci Chapel (Masaccio's frescoes), and the best trattorias in Florence.",
        "Piazzale Michelangelo (sunset) — the viewpoint above the city. Walk up rather than taking a taxi. Go an hour before sunset for the light on the Duomo.",
      ]},
      { t: "h2", v: "Tuscany Beyond Florence" },
      { t: "ul", v: [
        "Chianti Classico wine road — drive the SS222 between Florence and Siena through the heart of Sangiovese country. Stop at Radda in Chianti or Gaiole for a winery visit.",
        "Siena — Florence's eternal rival. The Piazza del Campo (scallop-shaped medieval plaza) and the Duomo (even more ornate than Florence's) are the reasons to come. The Palio (horse race in the square) runs in July and August.",
        "San Gimignano — the 'Manhattan of the Middle Ages' — 14 medieval towers still standing. Very crowded in summer; go in April or October.",
        "Val d'Orcia (UNESCO) — the most photographed landscape in Italy: rolling hills, lone cypress trees, and the hilltop towns of Pienza and Montepulciano.",
      ]},
    ],
  },

  {
    slug: "venice-travel-guide",
    title: "Venice Travel Guide: Yes It's Crowded. Go Anyway.",
    excerpt: "Venice is the most unique city on earth — 117 islands, 400 bridges, no cars, no roads, no logic. It's also overtouristed. Here's how to see it properly despite the crowds.",
    seo_title: "Venice Travel Guide 2025 | Things to Do, When to Go & Avoiding the Crowds",
    seo_description: "Complete Venice travel guide: Grand Canal, St Mark's Square, off-season advantages, day-tripper vs overnight debate, best islands (Murano, Burano, Torcello), and budget tips.",
    category: "destination-guide",
    destination_name: "Venice",
    destination_iata: "VCE",
    country: "Italy",
    region: "Southern Europe",
    continent: "Europe",
    hero_emoji: "🛶",
    best_time_to_visit: "November–March (fewest tourists; carnival in Feb) or May–June",
    tags: ["italy", "venice", "europe", "canals", "carnival", "gondola", "islands"],
    reading_time_mins: 9,
    featured: false,
    published: true,
    content_json: [
      { t: "p", v: "Venice was built on impossible foundations — 177 wooden piles hammered into the mud of a Adriatic lagoon, 1,500 years ago — and has been sinking millimetre by millimetre ever since. It gets 30 million visitors a year in a city of 50,000 residents (and falling). In July and August, the narrow calli (lanes) around San Marco are genuinely impassable at times. And yet. No other city on earth is remotely like this. Go. Just not in August." },
      { t: "facts", v: [
        { k: "Best time (autumn/winter)", val: "Nov–Mar: few crowds, dramatic light, acqua alta (flooding) possible Nov–Jan — atmospheric" },
        { k: "Best time (spring)", val: "Late Apr–early Jun: warm, manageable crowds" },
        { k: "Absolutely avoid", val: "Jul–Aug: extreme heat, extreme crowds, 30M tourists concentrated in tiny islands" },
        { k: "Carnival", val: "10 days before Mardi Gras (Feb/Mar) — mask festival, atmospheric but very crowded" },
        { k: "From Venice airport (VCE)", val: "Alilaguna boat 70 min to San Marco (~€15) or water taxi €100+" },
        { k: "Gondola", val: "€80–€120 for 30 min standard route — touristy but authentic to the city's transport history" },
        { k: "Day trip vs overnight", val: "Day-trippers are the problem. Stay overnight to experience the city after 6 PM when they leave." },
      ]},
      { t: "h2", v: "The Stay-Overnight Argument" },
      { t: "p", v: "The day-tripper buses arrive from Verona, Padova, and Mestre at 9 AM and leave at 5 PM. In between, the city is overwhelmed. After 6 PM — in the summer light, with the crowds gone and the palaces lit gold — Venice is completely different. Stay at least two nights. Breakfast on an empty calle, morning light on the Grand Canal, evening aperitivo at a bacaro (wine bar) — these things are impossible on a day trip." },
      { t: "h2", v: "What to Do" },
      { t: "ol", v: [
        "St. Mark's Basilica — book ahead to skip the queue; the golden Byzantine mosaics are extraordinary",
        "Doge's Palace — the political and judicial heart of the Republic of Venice for 700 years. The Bridge of Sighs. The scale of the council halls. Book ahead.",
        "Rialto Bridge and market — the fish and vegetable market on the Grand Canal side of Rialto is the most Venetian experience in the city. Go at 8 AM.",
        "Murano Island — glass-blowing workshops and the Glass Museum. 15 min by vaporetto. Afternoon.",
        "Burano Island — lace-making island of brightly painted fishermen's houses. The most Instagrammed island in the lagoon. 45 min by vaporetto.",
        "Dorsoduro neighbourhood — less touristed area south of the Grand Canal. The Gallerie dell'Accademia (Venice's main art museum) and the Peggy Guggenheim Collection are here.",
      ]},
    ],
  },

  {
    slug: "amalfi-coast-naples-guide",
    title: "Amalfi Coast & Naples: Cliffs, Pizza and the Ruins of Pompeii",
    excerpt: "The Amalfi Coast is one of the most photographed coastlines in the world. Naples is the chaotic, brilliant capital of the south. Together with Pompeii, they make one of Italy's greatest trips.",
    seo_title: "Amalfi Coast & Naples Guide 2025 | Best Towns, Pompeii & When to Visit",
    seo_description: "Complete Amalfi Coast and Naples travel guide: Positano, Ravello, Pompeii, best time to visit, how to get around (ferry vs road), Naples pizza, and Capri day trip.",
    category: "destination-guide",
    destination_name: "Amalfi Coast",
    destination_iata: "NAP",
    country: "Italy",
    region: "Southern Europe",
    continent: "Europe",
    hero_emoji: "🍋",
    best_time_to_visit: "May–June and September–October (avoid peak summer heat and crowds)",
    tags: ["italy", "amalfi", "naples", "positano", "pompeii", "europe", "coast"],
    reading_time_mins: 9,
    featured: false,
    published: true,
    content_json: [
      { t: "p", v: "The Amalfi Coast (Costiera Amalfitana) is 50 km of vertical cliffs, pastel villages glued to the rock face, terraced lemon groves, and turquoise sea. It's UNESCO World Heritage, overwhelmingly beautiful, and in July–August, overwhelmingly crowded. Naples, at the northern end of the Gulf, is its own extraordinary proposition — the city that invented the pizza Margherita, the gateway to Pompeii, and one of the most vibrantly chaotic urban experiences in Europe." },
      { t: "facts", v: [
        { k: "Best season", val: "May–Jun and Sep–Oct (22–28°C, ferry services running, roads manageable)" },
        { k: "Avoid", val: "Jul–Aug (extreme heat, road gridlock, Positano accommodation at 5x normal price)" },
        { k: "Main gateway", val: "Naples (NAP) — fly in, take ferry or SITA bus to coast" },
        { k: "Coastal transport", val: "Ferry between Positano, Amalfi, and Salerno is far better than the cliff road" },
        { k: "Road reality", val: "The SS163 coastal road is breathtaking and terrifying simultaneously — single-lane shared by buses and tour coaches" },
      ]},
      { t: "h2", v: "The Coast Town by Town" },
      { t: "ul", v: [
        "Positano — the most photographed village: tiered pink and white houses cascading to a small beach. Expensive, beautiful, extremely crowded in summer. The coastal path north to Praiano is quieter.",
        "Amalfi — the historic town that gave the coast its name. The Cathedral of Sant'Andrea, the paper museum, and the best chance to find a café that isn't tourist-priced.",
        "Ravello — the cultural town 300 m above the sea. Villa Rufolo and Villa Cimbrone gardens, the annual classical music festival (July–August), and the most spectacular views on the coast.",
        "Cetara — a working fishing village beyond the tourist circuit. Cetara anchovy paste (colatura di alici) is the most prized ingredient on the coast. The authentic version of what Positano pretends to be.",
      ]},
      { t: "h2", v: "Naples and Pompeii" },
      { t: "ul", v: [
        "Naples pizza — in its birthplace, a Margherita at L'Antica Pizzeria da Michele (the institution since 1870) or Sorbillo costs €5–8. The difference between Naples pizza and everywhere else is the water, the flour, and 150 years of practice.",
        "Pompeii — 30 min from Naples by Circumvesuviana train. The city frozen by the 79 AD eruption of Vesuvius. Walk the streets where the wheel ruts are still in the paving stones. Book timed entry online.",
        "Herculaneum (Ercolano) — smaller than Pompeii, better preserved, 2 stops earlier on the same train. The organic material (wooden furniture, food) survived here in ways that Pompeii's hotter burial didn't allow.",
        "Capri day trip — ferry from Naples (50 min) or Sorrento (25 min). The Blue Grotto, Via Krupp, and the gardens of Villa Jovis. June and September are the best months — July/August is chaos.",
      ]},
    ],
  },

  {
    slug: "algarve-faro-guide",
    title: "Algarve Travel Guide: Portugal's Southern Coast from Faro to Sagres",
    excerpt: "The Algarve has 300 days of sunshine per year, dramatic golden-rock sea stacks, and some of the cleanest beaches in Europe. Here's how to do it beyond the resort hotels.",
    seo_title: "Algarve Travel Guide 2025 | Best Beaches, Faro, Lagos & When to Visit",
    seo_description: "Complete Algarve guide: the best beaches (Praia da Marinha, Benagil, Meia Praia), Lagos old town, Sagres and Cape St Vincent, Faro, and best season for the Algarve.",
    category: "destination-guide",
    destination_name: "Algarve",
    destination_iata: "FAO",
    country: "Portugal",
    region: "Western Europe",
    continent: "Europe",
    hero_emoji: "🏖️",
    best_time_to_visit: "May–June and September–October (warm but not peak)",
    tags: ["portugal", "algarve", "faro", "lagos", "beach", "europe", "coast"],
    reading_time_mins: 8,
    featured: false,
    published: true,
    content_json: [
      { t: "p", v: "The Algarve is southern Portugal's 155 km Atlantic coastline — a sequence of spectacular sea stacks, hidden grottoes, and golden-sand beaches backed by terracotta cliffs. It's Portugal's most visited region for good reason: 300 sunshine days per year, warm Atlantic swimming (18–22°C in summer), fresh seafood at half the French Riviera price, and a sophisticated restaurant scene that has quietly become one of Europe's best coastal food destinations." },
      { t: "facts", v: [
        { k: "Airport", val: "Faro (FAO) — direct flights from most European cities (easyJet, Ryanair)" },
        { k: "Best season", val: "May–Jun and Sep–Oct (25–28°C, beach swimmable, much less crowded than Aug)" },
        { k: "Peak season", val: "Jul–Aug — very hot (35°C+), expensive, beaches crowded with British and German tourists" },
        { k: "Off-season", val: "Nov–Mar — quiet, mild (15–18°C), excellent for hiking, great value" },
        { k: "Getting around", val: "Car hire essential — buses exist but are slow; cycling along the Via Algarviana is possible" },
      ]},
      { t: "h2", v: "The Best Beaches (West to East)" },
      { t: "ul", v: [
        "Praia da Marinha (near Carvoeiro) — arguably Portugal's most beautiful beach: dramatic rock arches, turquoise water, golden cliffs. Accessible by cliff path or kayak from Benagil.",
        "Benagil Sea Cave — the most famous sea cave on the coast. Accessible only by kayak, paddleboard, or swimming (when calm). Book a guided kayak tour from Benagil beach.",
        "Meia Praia (Lagos) — a 4 km sweep of clean beach west of Lagos. Less dramatic geology than the eastern Algarve but more space and better swimming.",
        "Praia de Odeceixe (near Aljezur) — river mouth where the fresh water meets the ocean in a sheltered cove. Surfers, families, and the best of the western Algarve in one spot.",
        "Praia do Camilo (Lagos) — wooden staircase down to a sheltered cove between rock stacks. The most picturesque small beach near Lagos.",
      ]},
      { t: "h2", v: "Beyond the Beach" },
      { t: "ul", v: [
        "Lagos old town — a walled medieval centre with the Slave Market museum (the first in Europe, 1444), great restaurants, and a local character that survives despite heavy tourism.",
        "Sagres and Cape St Vincent — the southwestern-most point of continental Europe. The fortress where Henry the Navigator ran his school of navigation. The sunset here is elemental — just open ocean all the way to America.",
        "Faro old town — often overlooked as a transit point, the old city inside the walls is genuinely lovely: the cathedral, the Roman ruins, and the Ilha de Faro sandbar beach 20 min from the airport.",
        "Alentejo coast (just north) — quieter, wilder, surf beaches, no resort hotels. Drive north of Sagres along the Vicentine Coast Natural Park for the most dramatic and least visited coastline.",
      ]},
    ],
  },

  {
    slug: "madrid-travel-guide",
    title: "Madrid Travel Guide: The City That Lives at Night",
    excerpt: "Madrid operates on a schedule that would break other cities. Lunch at 3 PM, dinner at 10 PM, clubs that peak at 4 AM. It also has the Prado, the Retiro, and the best jamón on earth.",
    seo_title: "Madrid Travel Guide 2025 | Prado, Best Tapas Bars & When to Visit",
    seo_description: "Complete Madrid travel guide: Prado Museum, El Rastro flea market, best tapas bars, Retiro Park, La Latina neighbourhood, Flamenco, and when to visit Spain's capital.",
    category: "destination-guide",
    destination_name: "Madrid",
    destination_iata: "MAD",
    country: "Spain",
    region: "Southern Europe",
    continent: "Europe",
    hero_emoji: "🎭",
    best_time_to_visit: "March–May and September–November",
    tags: ["spain", "madrid", "europe", "tapas", "prado", "flamenco", "city-guide"],
    reading_time_mins: 9,
    featured: false,
    published: true,
    content_json: [
      { t: "p", v: "Madrid is the highest capital city in the European Union (667 m) and the city with the longest nights. Madrileños — people of Madrid — don't eat dinner until 9:30–10 PM and consider midnight a reasonable time to go out. The city is built for pleasure: the Prado is one of the world's great art museums, the Retiro park is one of Europe's finest urban gardens, and the tapas bars in La Latina serve the best cured ham on earth alongside the finest Spanish red wines." },
      { t: "facts", v: [
        { k: "Best season", val: "Mar–May and Sep–Nov (15–25°C, perfect weather, quieter than summer)" },
        { k: "Avoid", val: "Jul–Aug (40°C+, many locals flee, some restaurants closed)" },
        { k: "Airport", val: "Barajas (MAD) — Metro Line 8 to city centre: 30 min, €4.50" },
        { k: "Currency", val: "Euro (EUR)" },
        { k: "Daily budget", val: "€70–€120 (mid-range) — slightly cheaper than Barcelona" },
        { k: "Best areas", val: "La Latina (tapas), Malasaña (hipster), Chueca (LGBTQ+), Salamanca (upscale)" },
      ]},
      { t: "h2", v: "The Prado and the Art Triangle" },
      { t: "p", v: "The Paseo del Arte (Art Walk) connects three world-class museums within walking distance of each other. The Prado holds the world's finest collection of Spanish painting — Velázquez (Las Meninas), Goya (the Black Paintings), El Greco, Murillo, Zurbarán. The Reina Sofía has Picasso's Guernica (still overwhelming in person after 80 years) and the best collection of 20th-century Spanish art. The Thyssen-Bornemisza fills the gap between them: everything from medieval Italy to late 20th-century American art." },
      { t: "h2", v: "The Tapas Circuit (La Latina)" },
      { t: "ul", v: [
        "Cava Baja and Cava Alta streets in La Latina — the most concentrated tapas zone in Madrid. Walk the two streets, stop wherever is busy, order vermouth (vermú) and jamón",
        "El Rastro (Sunday flea market) — the enormous open-air market that takes over La Latina on Sunday mornings. 3,500 stalls. Browse for an hour, then have a beer in the surrounding bars",
        "Mercado de San Miguel — a covered iron market off Plaza Mayor. More curated than touristy; excellent pintxos and wine selection",
        "Botín (1725) — the world's oldest restaurant according to the Guinness Book. The roast suckling pig (cochinillo) is the thing to order",
        "Taberna El Sur — no-frills bacalao (salt cod) and vermouth. What Madrid actually tastes like",
      ]},
    ],
  },

  {
    slug: "seville-andalusia-guide",
    title: "Seville & Andalusia: Flamenco, Tapas and the Heart of Spain",
    excerpt: "Seville is where Spain's soul is kept — flamenco, sherry, the most dramatic cathedral in Spain, and tapas bars that serve free food with every drink.",
    seo_title: "Seville & Andalusia Travel Guide 2025 | Things to Do, Alhambra & Best Season",
    seo_description: "Complete Seville and Andalusia guide: Real Alcázar, flamenco shows, Córdoba Mezquita, Granada Alhambra, Ronda, best season, free tapas culture, and practical tips.",
    category: "destination-guide",
    destination_name: "Seville",
    destination_iata: "SVQ",
    country: "Spain",
    region: "Southern Europe",
    continent: "Europe",
    hero_emoji: "💃",
    best_time_to_visit: "March–May and October–November (avoid summer at all costs)",
    tags: ["spain", "seville", "andalusia", "flamenco", "alhambra", "europe", "tapas"],
    reading_time_mins: 9,
    featured: false,
    published: true,
    content_json: [
      { t: "p", v: "Seville is the capital of Andalusia and the city that feels most like the Spain of imagination — orange trees in the streets, flamenco in courtyards, Gothic cathedrals the size of city blocks, and a culture of outdoor evening life (the paseo) that continues until midnight regardless of the day of the week. The Semana Santa (Holy Week, Easter) and Feria de Abril (April Fair) are two of Europe's greatest festivals." },
      { t: "facts", v: [
        { k: "Best season", val: "Mar–May and Oct–Nov (18–26°C — perfect)" },
        { k: "AVOID", val: "June–September: 40–46°C heat. Seville regularly records Spain's highest temperatures." },
        { k: "Airport", val: "Seville (SVQ) — or fly Malaga (AGP) and day-trip by train" },
        { k: "Free tapas culture", val: "In many Seville bars, tapas come free with each drink — a system increasingly rare even in southern Spain" },
        { k: "Day trips from Seville", val: "Córdoba (45 min by AVE high-speed train), Ronda (2 hrs by bus/car), Doñana National Park (wildlife, 2 hrs)" },
        { k: "Granada", val: "2.5 hrs by AVE — the Alhambra requires booking months ahead" },
      ]},
      { t: "h2", v: "Seville: The Essential List" },
      { t: "ol", v: [
        "Real Alcázar — the royal palace complex, still used by the Spanish royal family. A Moorish palace converted by Christian kings into something that combines both beautifully. Book timed entry well ahead — daily visitor limits.",
        "Seville Cathedral — the largest Gothic cathedral in the world. Columbus is buried here (his tomb, carried by four life-sized kings). Climb the Giralda minaret-turned-bell-tower for the best view over Seville.",
        "Barrio Santa Cruz — the old Jewish quarter. White-washed walls, flower-draped windows, hidden plazas. Walk without a map for an hour.",
        "Flamenco show — Tablao El Arenal and Casa de la Memoria are both authentic. Go for the late show (10 PM) when the performers are warmed up.",
        "El Mercado Lonja del Barranco and the Triana Market — Triana neighbourhood across the Guadalquivir river is the working-class Seville that tourists miss.",
      ]},
      { t: "h2", v: "Andalusia Beyond Seville" },
      { t: "ul", v: [
        "Granada and the Alhambra — the 13th-century Nasrid palace is the finest example of Moorish architecture in the world. Book the Nasrid Palaces months ahead; tickets sell out.",
        "Córdoba Mezquita — a mosque converted into a cathedral in the most extraordinary way: a Gothic nave inserted into the middle of a forest of 856 columns and red-and-white arches. Staggering.",
        "Ronda — a white hilltop town split by the El Tajo gorge. The Puente Nuevo bridge over the 120 m gorge is one of Spain's most dramatic sights.",
        "Jerez de la Frontera (Sherry) — the birthplace of sherry. González Byass and Domecq wineries offer fascinating tours of the sherry production process. The flamenco scene here is the most authentic in Andalusia.",
      ]},
    ],
  },

  {
    slug: "french-riviera-nice-guide",
    title: "French Riviera: Nice, Monaco, Cannes & the Côte d'Azur",
    excerpt: "The Côte d'Azur has been the playground of European royalty, Russian oligarchs, and American artists since the 19th century. Here's how to enjoy it without spending like one.",
    seo_title: "French Riviera Travel Guide 2025 | Nice, Monaco, Cannes & Best Season",
    seo_description: "Complete French Riviera guide: Nice old town, Monaco, Cannes, Antibes, Villefranche-sur-Mer, the Corniche roads, best time to visit, budget tips, and how to get around.",
    category: "destination-guide",
    destination_name: "Nice",
    destination_iata: "NCE",
    country: "France",
    region: "Western Europe",
    continent: "Europe",
    hero_emoji: "🌊",
    best_time_to_visit: "May–June and September–October",
    tags: ["france", "nice", "monaco", "cannes", "riviera", "europe", "coast"],
    reading_time_mins: 9,
    featured: false,
    published: true,
    content_json: [
      { t: "p", v: "The French Riviera (Côte d'Azur) is 115 km of Mediterranean coastline between Menton (on the Italian border) and Cassis (near Marseille). The light here is extraordinary — the reason that Matisse, Picasso, Renoir, and Cézanne all relocated to the south. The sea is a shade of blue that seems to not follow normal colour rules. Monaco is absurd and wonderful. And the 900-year-old old town of Nice is legitimately one of Europe's finest urban spaces." },
      { t: "facts", v: [
        { k: "Best season", val: "May–Jun and Sep–Oct (22–28°C, fewer crowds, sea still warm)" },
        { k: "Avoid (for price)", val: "Cannes Film Festival (mid-May) and Monaco Grand Prix (late May) — prices triple" },
        { k: "Peak season", val: "Jul–Aug — very crowded, very expensive, but the sea at its warmest (24–26°C)" },
        { k: "Airport", val: "Nice Côte d'Azur (NCE) — the second busiest airport in France" },
        { k: "Getting around", val: "Train along the coast (Nice → Monaco → Menton, 30 min) is excellent. Car for the Corniche roads." },
      ]},
      { t: "h2", v: "Nice: The Underrated Capital" },
      { t: "ul", v: [
        "Vieux-Nice (Old Town) — narrow lanes of Italian-influenced Baroque architecture, market stalls on Cours Saleya, socca (chickpea pancake) from street vendors. The most atmospheric old town on the Riviera.",
        "Promenade des Anglais — the famous seafront boulevard. Nice's beach is pebble, not sand — bring shoes to walk into the water.",
        "Musée Matisse — a Roman villa converted to house Henri Matisse's donation to his adopted city. Free on first Sunday of each month.",
        "Castle Hill (Colline du Château) — the ruins of the original medieval city, now a park with the best view of Nice and the Baie des Anges. Walk up, take the elevator down.",
      ]},
      { t: "h2", v: "The Day Trips" },
      { t: "ul", v: [
        "Monaco (30 min by train) — the casino, the Prince's Palace, the Formula 1 circuit (you can drive it in a rental car outside race week), and the Oceanographic Museum founded by Jacques Cousteau.",
        "Èze Village (between Nice and Monaco) — a perched medieval village 400 m above the sea. The coastal path from the village down to the sea (Nietzsche Path) is 2 km of dizzy views.",
        "The Grande Corniche — drive or cycle the highest coastal road (500 m above the sea) between Nice and Monaco. The views are as dramatic as roads get in Europe.",
        "Antibes (20 min west by train) — the Picasso Museum in the Château Grimaldi (Picasso's studio from 1946), the old Provençal market, and the Cap d'Antibes peninsula.",
      ]},
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // NORTH & CENTRAL AMERICA — additional
  // ═══════════════════════════════════════════════════════════

  {
    slug: "puerto-vallarta-guide",
    title: "Puerto Vallarta & the Riviera Nayarit: Mexico's Pacific Paradise",
    excerpt: "Puerto Vallarta has turned its back on the Cancún-style resort model and become something genuinely interesting — old colonial town, world-class sport fishing, and a restaurant scene that punches well above its size.",
    seo_title: "Puerto Vallarta Travel Guide 2025 | Things to Do, Best Season & Tips",
    seo_description: "Complete Puerto Vallarta guide: Zona Romántica, Malecón, whale watching season, Sayulita day trip, Riviera Nayarit, best restaurants, and when to visit Mexico's Pacific coast.",
    category: "destination-guide",
    destination_name: "Puerto Vallarta",
    destination_iata: "PVR",
    country: "Mexico",
    region: "North America",
    continent: "North America",
    hero_emoji: "🐋",
    best_time_to_visit: "November–April (dry season; whale watching Dec–Mar)",
    tags: ["mexico", "puerto-vallarta", "pacific", "north-america", "beach", "whales"],
    reading_time_mins: 8,
    featured: false,
    published: true,
    content_json: [
      { t: "p", v: "Puerto Vallarta sits on Banderas Bay — one of the largest natural bays on the Pacific coast — in a crescent of jungle-covered hills meeting an impossibly blue ocean. The Zona Romántica (Old Town), with its cobblestone streets, painted houses, and Malecón seafront promenade, has retained more character than most Mexican beach destinations. It's also the best place in Mexico to watch humpback whales." },
      { t: "facts", v: [
        { k: "Best season", val: "Nov–Apr (dry, 24–30°C, calm Pacific)" },
        { k: "Whale season", val: "Dec–March: humpback whales calve and mate in Banderas Bay" },
        { k: "Avoid", val: "Jun–Oct (hurricane and rainy season — heavy tropical storms possible)" },
        { k: "Airport", val: "Gustavo Díaz Ordaz (PVR) — 8 km from city centre" },
        { k: "Currency", val: "MXN — USD widely accepted in tourist zones" },
        { k: "Best areas", val: "Zona Romántica (most atmospheric), Hotel Zone (resort strip)" },
      ]},
      { t: "h2", v: "Top Things to Do" },
      { t: "ol", v: [
        "Whale watching (Dec–March) — Banderas Bay is one of the best places in the world to see humpback whales. 3–4 hour boat trips with certified operators. Breaching, tail slaps, and song recordings from underwater hydrophones.",
        "Zona Romántica exploration — the old town south of the Río Cuale. The church of Guadalupe (the town's landmark), the Malecón sculpture walk, and the farmers' market on Saturdays.",
        "Los Arcos Marine Sanctuary snorkelling/diving — a group of granite arches off the coast 20 km south, sheltering one of the best marine environments on the Pacific coast.",
        "Sayulita day trip (45 min north) — a small bohemian surf village in Nayarit state. Artisan markets, good surf breaks, excellent tacos. Significantly more relaxed than Vallarta.",
        "Jungle zip-lining — the Sierra Madre mountains rise directly behind the city. Los Veranos Canopy tour runs through the jungle above the city.",
        "Sport fishing — Banderas Bay is one of Mexico's premier sport fishing destinations: marlin, sailfish, mahi-mahi, and yellow-fin tuna.",
      ]},
      { t: "tip", v: "The Malecón at night — the 2 km seafront walkway lined with sculptures and restaurants — is the best free evening activity in Puerto Vallarta. Walk south to the Zona Romántica and end at one of the rooftop bars for sunset." },
    ],
  },

  {
    slug: "cabo-san-lucas-la-paz-guide",
    title: "Los Cabos, Cabo San Lucas & La Paz: Baja California's Tip",
    excerpt: "Cabo San Lucas is where the Pacific meets the Sea of Cortez at land's end — dramatic, expensive, and party-focused. La Paz, two hours north, is where Mexico actually lives.",
    seo_title: "Cabo San Lucas & La Paz Guide 2025 | Arch of Cabo, Whale Sharks & Tips",
    seo_description: "Complete guide to Los Cabos, Cabo San Lucas, and La Paz: the Arch, snorkelling with whale sharks (La Paz), best beaches, when to visit, and the best of Baja California.",
    category: "destination-guide",
    destination_name: "Los Cabos",
    destination_iata: "SJD",
    country: "Mexico",
    region: "North America",
    continent: "North America",
    hero_emoji: "🦈",
    best_time_to_visit: "November–May (dry season; whale sharks at La Paz: Oct–Apr)",
    tags: ["mexico", "cabo", "la-paz", "baja", "whale-sharks", "north-america", "pacific"],
    reading_time_mins: 8,
    featured: false,
    published: true,
    content_json: [
      { t: "p", v: "The Baja California peninsula ends at Cabo San Lucas — a thin finger of desert rock where the blue Pacific meets the turquoise Sea of Cortez. The dramatic Arch of Cabo San Lucas (El Arco) marks the meeting point. Cabo itself is a resort city of high-end hotels and spring break energy. La Paz, 160 km north on the calmer Sea of Cortez side, is a real Mexican city with the best sea kayaking and whale shark snorkelling in the world." },
      { t: "facts", v: [
        { k: "Airport", val: "Los Cabos (SJD) — all international flights land here" },
        { k: "Best season", val: "Nov–May (dry, 22–30°C)" },
        { k: "Avoid", val: "Aug–Oct (hurricane season — September highest risk)" },
        { k: "Whale shark season at La Paz", val: "October–April (peak: Nov–Mar) — the largest fish in the sea" },
        { k: "Cabo vs La Paz", val: "Cabo: resorts, nightlife, fishing, tourists. La Paz: authentic, kayaking, whale sharks, real Mexico." },
        { k: "La Paz access", val: "2 hrs by car from Cabo, or 1-hr flight from LAX/LA direct" },
      ]},
      { t: "h2", v: "Cabo San Lucas: The Essentials" },
      { t: "ul", v: [
        "El Arco (The Arch) — the granite sea arch at Land's End where the two oceans meet. Take the glass-bottomed boat from the marina (30 min, $15). Sea lion colony at the base.",
        "Playa del Amor (Lover's Beach) — accessible only by boat; the only beach where Pacific meets the Cortez. Dramatic and beautiful.",
        "Sport fishing — among the world's premier marlin grounds. Full-day charter from the marina.",
        "Sunset cocktail cruises — touristy but the sunset over El Arco is genuinely spectacular.",
        "San José del Cabo (20 min north) — the quieter, more colonial town in the Los Cabos corridor. Art galleries, craft shops, and the best local restaurants.",
      ]},
      { t: "h2", v: "La Paz: Where Baja Gets Serious" },
      { t: "ul", v: [
        "Whale shark snorkelling — the world's most reliable whale shark aggregation. 5–12 m gentle giants feeding on plankton in the warm Cortez water. Permitted snorkelling tours ($80–$110) run daily in season. Non-extractive, conservation-managed. Extraordinary.",
        "Sea kayaking — the Sea of Cortez has some of the world's finest sea kayaking: Espíritu Santo Island (UNESCO biosphere), sea lions, dolphins, manta rays. Multi-day guided expeditions available.",
        "Malecón evening walk — La Paz's waterfront boulevard. The best sunset in Baja and the most relaxed beach-city atmosphere in Mexico.",
        "Todos Santos (90 min west) — a small arts town on the Pacific side. The Hotel California (disputed connection to the Eagles song), galleries, and surprisingly good restaurants.",
      ]},
    ],
  },

  {
    slug: "panama-city-guide",
    title: "Panama City: Canal, Skyscrapers and the Casco Viejo",
    excerpt: "Panama City is one of the most surprising cities in Latin America — a skyline that rivals Miami, a UNESCO colonial old town, and one of the greatest engineering achievements in history 30 minutes away.",
    seo_title: "Panama City Travel Guide 2025 | Canal, Casco Viejo & Things to Do",
    seo_description: "Complete Panama City travel guide: Panama Canal (Miraflores Locks), Casco Viejo UNESCO district, Amador Causeway, Bocas del Toro connection, and best time to visit.",
    category: "destination-guide",
    destination_name: "Panama City",
    destination_iata: "PTY",
    country: "Panama",
    region: "Central America",
    continent: "North America",
    hero_emoji: "🚢",
    best_time_to_visit: "December–April (dry season)",
    tags: ["panama", "panama-city", "canal", "central-america", "casco-viejo", "north-america"],
    reading_time_mins: 8,
    featured: false,
    published: true,
    content_json: [
      { t: "p", v: "Panama City sits at the Pacific end of the canal that changed the world — a 77 km cut through the Continental Divide that shortened the shipping route between Atlantic and Pacific by 13,000 km. The city that grew around this engineering miracle is one of Latin America's most modern — 50+ skyscrapers, a banking sector that gives it a Switzerland-of-the-Americas feel, and the UNESCO-listed Casco Viejo colonial quarter that makes it something real." },
      { t: "facts", v: [
        { k: "Best season", val: "Dec–Apr (dry season, 28–32°C, clear skies)" },
        { k: "Avoid", val: "May–Nov (heavy rain daily — though still functional)" },
        { k: "Airport", val: "Tocumen International (PTY) — Central America's main hub" },
        { k: "Currency", val: "US Dollar — Panama uses USD as its official currency" },
        { k: "Daily budget", val: "$60–$100 USD (mid-range)" },
        { k: "Bocas del Toro", val: "50-min flight from PTY — Caribbean islands with excellent snorkelling and a backpacker scene" },
      ]},
      { t: "h2", v: "The Panama Canal: What to Know" },
      { t: "p", v: "The Panama Canal connects the Atlantic (Caribbean) and Pacific Oceans through 77 km of locks, lakes, and cuts. The Miraflores Visitor Centre (30 min from city) has the best viewing platform for watching ships transit the locks — the process of raising and lowering 50,000-tonne vessels by 26 m using only gravity and water is astonishing even when you understand the engineering. Arrive mid-morning for the most ship traffic. A Pacific-to-Atlantic transit by passenger vessel is possible through specialised boat bookings (multi-day experience)." },
      { t: "h2", v: "Casco Viejo: The Colonial Quarter" },
      { t: "p", v: "Casco Viejo (also called Casco Antiguo) is the UNESCO-listed colonial peninsula founded in 1673 after pirates sacked the original settlement. It's an extraordinary urban renovation success story — 20 years ago it was a crumbling slum; today it's a neighbourhood of restored palaces, rooftop bars, boutique hotels, and Panama's best restaurants. The Plaza de Francia, the ruins of the old cathedral (destroyed by pirate Henry Morgan in 1671), and the French Embassy are all here." },
      { t: "h2", v: "Day Trips and Onward Travel" },
      { t: "ul", v: [
        "Bocas del Toro (50 min flight) — Caribbean island archipelago. Snorkelling the coral gardens of Bastimentos Island, red-frog beach, and the most laid-back party scene in Central America.",
        "Barro Colorado Island — a tropical research island in Gatún Lake (the canal reservoir). Guided research tours reveal one of the most biodiverse forest patches in the Americas.",
        "San Blas Islands (Guna Yala) — 365 coral islands of the indigenous Guna people. Pristine beaches, reef snorkelling, and one of the most culturally intact indigenous communities in Latin America. Day trips or overnight stays in Guna-owned lodges.",
        "Portobelo — a colonial fort town on the Caribbean coast. UNESCO listed, somewhat decayed, extraordinarily atmospheric.",
      ]},
    ],
  },

];
